### ISSUE TITLE
How to NQuery Predicate on key?

### ISSUE THREAD

**Issue by vanvanni** [NivixX/NDatabase#13]
Hi,

I want to query on the Key (data_key) and a other indexed field. Only I could not make this work, I tried achieving this with:
```
$.key == %s && $.type == PLACE
```

```
$.data_key == %s && $.type == PLACE
```

```
$ == %s && $.type == PLACE
```

Also I later tried adding a index to the key by using this in my entity:
```
    @JsonProperty("key")
    @Indexed
    protected String key;
```

All did not succeed, so what is the right way to approach this?

**Comment by NivixX** [comment]
Hello, 

The key is unique, so why would you like to query + another predicate ? Since your entity has an unique id, mixing key query and value query isn't very relevant (because searching by key will return you only one unique result)

Also could you share the details about your entity class and what database type you use ?


Here is an example of using query

`public class MyData extends NEntity<UUID> {

    @JsonProperty("place")
    @Indexed
    private String place;
    
    // Getter and setter
}`

`
Repository<UUID, MyData> myDataRepository = NDatabase.api().getOrCreateRepository(MyData.class);

// Insert data
MyData myData = new MyData();
UUID id = UUID.randomUUID();
myData.setKey(id);
myData.setPlace("MyPlace");
myDataRepository.insert(myData);

// Get by key
myDataRepository.get(id);

// Get by place
myDataRepository.find(NQuery.predicate("$.place == MyPlace"));
        `

**Comment by vanvanni** [comment]
> Hello,
> 
> The key is unique, so why would you like to query + another predicate ? Since your entity has an unique id, mixing key query and value query isn't very relevant (because searching by key will return you only one unique result)
> 
> Also could you share the details about your entity class and what database type you use ?
> 
> Here is an example of using query
> 
> ```
> public class MyData extends NEntity<UUID> {
> 
>     @JsonProperty("place")
>     @Indexed
>     private String place;
>     
>     // Getter and setter
> }
> ```
> 
> ```
> Repository<UUID, MyData> myDataRepository = NDatabase.api().getOrCreateRepository(MyData.class);
> 
> // Insert data
> MyData myData = new MyData();
> UUID id = UUID.randomUUID();
> myData.setKey(id);
> myData.setPlace("MyPlace");
> myDataRepository.insert(myData);
> 
> // Get by key
> myDataRepository.get(id);
> 
> // Get by place
> myDataRepository.find(NQuery.predicate("$.place == MyPlace"));
> ```

Hi, what I want todo is insert a record for a Material Type with a value of how often it is placed/broken. Therefore I created two records for each material (if used) and update it's value.

So when a block is placed I want to find the records based of Material and Type (PLACE/BREAK).  

Here is my Entity:
```
@NTable(name = "statistics")
public class Statistic extends NEntity<String> {
    @JsonProperty("type")
    @Indexed
    private String type;

    @JsonProperty("value")
    private int value;
    
    public Statistic() {
    }

    public Statistic(String key, String type) {
        this.key = key;
        this.type = type;
    }

    public String getType() {
        return this.type;
    }

    public int getValue() {
        return this.value;
    }

    public void setValue(int value) {
        this.value = value;
    }

    public void increaseValue(int step) {
        this.setValue(this.getValue() + step);
    }
}
```

I now try this code, this works for the first time, it does not find a record and insert one, but after a insert. I still get no rows back.
```
 repo.streamAndFindOneAsync(($) -> ($.getKey() == BLOCK_NAME && $.getType() == "PLACE")).thenAsync((statistic, throwable) -> {
            System.out.println(throwable);
            System.out.println(statistic);
            if(throwable != null || (statistic == null || statistic.get() == null)) {
                System.out.println("Adding block");
                Statistic blockStatistic = new Statistic(BLOCK_NAME, "PLACE");
                blockStatistic.setValue(1);
                repo.insert(blockStatistic);
                return;
            }

            System.out.println("Updating block");

            Statistic model = statistic.get();
            System.out.println(BLOCK_NAME + ": " + model.getValue());
            model.increaseValue(1);
            System.out.println(BLOCK_NAME + ": " + model.getValue());
            repo.upsertAsync(model);
        });
```

**Comment by NivixX** [comment]
Ok, I see more or less what you want to do. You want to increment a block break count or block break place for each material type. Therefore I don't get why you still want to query by key, but it's actually doable if you do the following approach (copy the material in your entity).
I've changed a little bit your approach and write a test to validate it work:

Your entity :
```
@NTable(name = "block_statistics")
// Note the key is the MATERIAL type
public class BlockStatistics extends NEntity<String> {

@Indexed
private String materialType;

@Indexed
private long breakCount;

@Indexed
private long placeCount;
```

Full working example
```
@Test
public void insert_and_increment_and_then_get() {
    Repository<String, BlockStatistics> repo = NDatabase.api().getOrCreateRepository(BlockStatistics.class);
    String diamond = Material.DIAMOND.toString();
    BlockStatistics blockStatistics = new BlockStatistics();
    blockStatistics.setKey(diamond);
    blockStatistics.setMaterialType(diamond);

    // insert
    repo.insert(blockStatistics);

    // increment break
    BlockStatistics diamondBlockStats = repo.get(diamond);
    diamondBlockStats.setBreakCount(diamondBlockStats.getBreakCount()+1);
    repo.update(diamondBlockStats);

    // search by diamond and breakCount >= 1
    Optional<BlockStatistics> search =
            repo.findOne(NQuery.predicate("$.materialType == DIAMOND && breakCount >= 1"));
    assert search.isPresent();
}
```

**Comment by vanvanni** [comment]
> Ok, I see more or less what you want to do. You want to increment a block break count or block break place for each material type. Therefore I don't get why you still want to query by key, but it's actually doable if you do the following approach (copy the material in your entity). I've changed a little bit your approach and write a test to validate it work:
> 
> Your entity :
> 
> ```
> @NTable(name = "block_statistics")
> // Note the key is the MATERIAL type
> public class BlockStatistics extends NEntity<String> {
> 
> @Indexed
> private String materialType;
> 
> @Indexed
> private long breakCount;
> 
> @Indexed
> private long placeCount;
> ```
> 
> Full working example
> 
> ```
> @Test
> public void insert_and_increment_and_then_get() {
>     Repository<String, BlockStatistics> repo = NDatabase.api().getOrCreateRepository(BlockStatistics.class);
>     String diamond = Material.DIAMOND.toString();
>     BlockStatistics blockStatistics = new BlockStatistics();
>     blockStatistics.setKey(diamond);
>     blockStatistics.setMaterialType(diamond);
> 
>     // insert
>     repo.insert(blockStatistics);
> 
>     // increment break
>     BlockStatistics diamondBlockStats = repo.get(diamond);
>     diamondBlockStats.setBreakCount(diamondBlockStats.getBreakCount()+1);
>     repo.update(diamondBlockStats);
> 
>     // search by diamond and breakCount >= 1
>     Optional<BlockStatistics> search =
>             repo.findOne(NQuery.predicate("$.materialType == DIAMOND && breakCount >= 1"));
>     assert search.isPresent();
> }
> ```
> 
> I've changed a little bit your data structure, by replacing your notion of "type" and include "break" and "place" type directly in the same entity (as it has the same key)

Right I see your approach, no clue why I did not think of this myself. Thanks! Love your library is very fluent
