### ISSUE TITLE
Issue on Home System

### ISSUE THREAD

**Issue by davidegrigioni** [NivixX/NDatabase#17]
I'm trying to do a home system using NDatabase and my current issue is the following:
- When I use the /sethome command it sets the home but when I use the /home command it says "home <home> doesn't exist"

Here is the Home Model: https://gist.github.com/davidegrigioni/03f64f69e17b942c309a543f1ad23dfe
HomeCommand: https://gist.github.com/davidegrigioni/f3e192e15af6915033e38d1f11e251bc
Player Model: https://gist.github.com/davidegrigioni/79866b7a15dd9f346ae07b1fbd0a1084

**Comment by davidegrigioni** [comment]
Also my goal is to insert the homes in the playerprofile but i'm unsure on how to do it

**Comment by NivixX** [comment]
Hello, you don't have to escape " for strings

Replace 
String.format("$.homeName == \"%s\"", homeName);

With 
String.format("$.homeName == %s", homeName);

I'm thinking of improving the NQuery, by adding debug logging of the actually SQL/MongoDB query executed

Let me know if it worked for you

**Comment by NivixX** [comment]
> Also my goal is to insert the homes in the playerprofile but i'm unsure on how to do it

Yes you can do it by changing the approach, how you are mapping the association between a player and home. You can add an indexed field playerId in HomeEntity and then when you want to get all homes of a player you can query the home repository where playerId equals your target player

After you have this list, you can set a list of home in your PlayerProfile with a transient field (that is ignored for db) or even better, you can separate your Entity object and your Domain (bukkit) object to have a more domain Driven approach by separating your data definition with your actual domain object that manipulate bukkit related API

**Comment by davidegrigioni** [comment]
> > Also my goal is to insert the homes in the playerprofile but i'm unsure on how to do it
> 
> Yes you can do it by changing the approach, how you are mapping the association between a player and home. You can add an indexed field playerId in HomeEntity and then when you want to get all homes of a player you can query the home repository where playerId equals your target player
> 
> After you have this list, you can set a list of home in your PlayerProfile with a transient field (that is ignored for db) or even better, you can separate your Entity object and your Domain (bukkit) object to have a more domain Driven approach by separating your data definition with your actual domain object that manipulate bukkit related API

Can you give me an Example? Sorry I think i'll understand better

**Comment by NivixX** [comment]
I don't have my laptop with me but let me do with pseudo code so you get the idea.

Assuming you want to load player profile (death, kills,...) and you also want to load player's home, and a player can have multiple homes:

Class HomeEntity 
// Here I recommend you to put a random ID as the key, because a key is unique, so you can't use player ID as the key

// Add another field, a reference to the player
private UUID playerId;

Class PlayerProfileEntity
// Kills, death,...

// A new transient field that will be ignored when saving PlayerProfileEntity
private transient List<HomeEntity> homes;

Method load player(Player player)
PlayerProfileEntity playerProfile = profile repository.find(player.getId())
List<HomeEntity> homes = homeRepository.find($.playerId == player.getId())
PlayerProfile.setHomes(homes)

Should work

- -
Also I see that you know how to use serialize and deserialize (you used to serialize Location), so actually if you don't need to index player homes, you can just create a Homes object that contains home name and location list, and you can store it on PlayerProfileEntity as well, this field will be automatically stored as json

**Comment by davidegrigioni** [comment]
> I don't have my laptop with me but let me do with pseudo code so you get the idea.
> 
> Assuming you want to load player profile (death, kills,...) and you also want to load player's home, and a player can have multiple homes:
> 
> Class HomeEntity // Here I recommend you to put a random ID as the key, because a key is unique, so you can't use player ID as the key
> 
> // Add another field, a reference to the player private UUID playerId;
> 
> Class PlayerProfileEntity // Kills, death,...
> 
> // A new transient field that will be ignored when saving PlayerProfileEntity private transient List homes;
> 
> Method load player(Player player) PlayerProfileEntity playerProfile = profile repository.find(player.getId()) List homes = homeRepository.find($.playerId == player.getId()) PlayerProfile.setHomes(homes)
> 
> Should work
> 
> * 
> 
> Also I see that you know how to use serialize and deserialize (you used to serialize Location), so actually if you don't need to index player homes, you can just create a Homes object that contains home name and location list, and you can store it on PlayerProfileEntity as well, this field will be automatically stored as json

HomeCommand: https://gist.github.com/davidegrigioni/e8bb0b889b40e4634a0863461f4dbeca
HomeModel: https://gist.github.com/davidegrigioni/541b7d2d20facab9b9ce188ed0950807
PlayerModel: https://gist.github.com/davidegrigioni/3ef9b0c4ae5d1e14371e674e0504ce76

Also right now when i for example use /sethome ciao it will send the "home ciao has been set" every time i spam the command, when i reload it will give me the NDatabaseException SQLLITE_CONSTRAINT_PRIMARYKEY error.

The profile will be loaded on player join and for that it works as i want.
What i want is that when i type /sethome home it will set the home in the playerprofile entity and when i type /home home it will check if the home already exists and if it exist it will teleport to that home.

I'm really unsure on how to do that i'm doing this since days so hah, i have a bit of headache right now

**Comment by davidegrigioni** [comment]
Another Issue I found is when i reload the server even if i try to set another home (lets say /sethome ciao2) it will say that it already exists even if it doesn't exist

**Comment by NivixX** [comment]
From the gist you're providing I see few issues

On the sethome cmd you create a Home object without setting the homeOwner, so when you execute the home command, it won't find your home because the homeOwner is null

Also in your home command, when you do your query, you should check for playerId and home name, because if 2 players has home with same names it won't work
(.$homeName == home name && $.homeOwner == playerId)

For your spam issue, as the code you execute is async, you should prevent your player from executing cmd if the async process is not finished

**Comment by davidegrigioni** [comment]
> From the gist you're providing I see few issues
> 
> On the sethome cmd you create a Home object without setting the homeOwner, so when you execute the home command, it won't find your home because the homeOwner is null
> 
> Also in your home command, when you do your query, you should check for playerId and home name, because if 2 players has home with same names it won't work (.$homeName == home name && $.homeOwner == playerId)
> 
> For your spam issue, as the code you execute is async, you should prevent your player from executing cmd if the async process is not finished

https://gist.github.com/davidegrigioni/942bb44466e1eeec5fd49ffaa10c83eb

Okay it does indeed work now but i still dont understand the issue when i restart the server it will say:
<img width="326" alt="{6653BA94-0C44-48E1-88CC-DDB86EB15893}" src="https://github.com/user-attachments/assets/a5a53002-a75b-4c49-b6b6-fb5de408126d">
when trying to set new homes, why?

**Comment by NivixX** [comment]
I assume it may be because of the IDUtils.generateId()
I don't have the class but maybe it generate the same int key when you restart ?
I recommend using UUID as key and use UUID.randomUUID()

**Comment by NivixX** [comment]
When you develop, I suggest you to set NDatabase config to debug true in the config, it will print you all the inserted data, so you will have better info

**Comment by davidegrigioni** [comment]
> I assume it may be because of the IDUtils.generateId() I don't have the class but maybe it generate the same int key when you restart ? I recommend using UUID as key and use UUID.randomUUID()

Also i got it working:
https://gist.github.com/davidegrigioni/f17f8df996d189a0f49fd5954778714b

the final thing i need to do is on the playerprofilecommand:
https://gist.github.com/davidegrigioni/cd5c20436a1126a255d1b92cdc89b087

When i execute it it will send an empty list even if i set multiple homes, I modified the PlayerModel:
https://gist.github.com/davidegrigioni/71896672dafb07532bfc26e3eb0ae212

To actually save the homes, what i'm missing to make it work as intended?

**Comment by NivixX** [comment]
You cannot save a list of NEntity inside a NEntity
If you really want to save a List of "Home" in your playerProfile, your Home object must not be a NEntity, but a simple object. Then you will see in the debug mode that a list of home will be saved inside your user profile as a array of json (but you won't have a Home repository).

So given your current data structure, if you want to get all homes for a player, I recommend you to fetch them separately using Home repository and find($.homeOwner == playerId)

**Comment by davidegrigioni** [comment]
> You cannot save a list of NEntity inside a NEntity If you really want to save a List of "Home" in your playerProfile, your Home object must not be a NEntity, but a simple object. Then you will see in the debug mode that a list of home will be saved inside your user profile as a array of json (but you won't have a Home repository).
> 
> So given your current data structure, if you want to get all homes for a player, I recommend you to fetch them separately using Home repository and find($.homeOwner == playerId)

Do you think it would make more sense to just create a simple object for the homes and then store it in the database? as long as they are stored in the database for me is not a problem to just create the simple object

**Comment by NivixX** [comment]
It's up to you, if you create a Homes object and you store it inside playerProfile, you will only need one table, but in the other side, as an admin, you won't be able to find all homes of a specific player (because no longer indexed) so I would recommend to have homes and playerProfile separated

**Comment by davidegrigioni** [comment]
> It's up to you, if you create a Homes object and you store it inside playerProfile, you will only need one table, but in the other side, as an admin, you won't be able to find all homes of a specific player (because no longer indexed) so I would recommend to have homes and playerProfile separated

Perfect I have everything, thanks alot for your help! I'll close the issue!
