### ISSUE TITLE
Error with getOrCreateRepository() method.

### ISSUE THREAD

**Issue by RE4ERKA** [NivixX/NDatabase#2]
PlayerStats class:
```
@NTable(name = "player_statistics")
public class PlayerStats extends NEntity<UUID> {

    @JsonProperty("killCount")
    private int kills;

    @JsonProperty("deathCount")
    private int deaths;

    public PlayerStats() {}
}
```

Method:
```
Repository<UUID, PlayerStats> repository = NDatabase.api().getOrCreateRepository(PlayerStats.class);
```

![image](https://user-images.githubusercontent.com/66727581/217062060-95d78eb6-2f61-4b48-a381-e01f5cbc4d17.png)

**Comment by NivixX** [comment]
Hello, thank you for the report, can you send me your java version ?
`java -version`
I'll look at this and fix that asap.

**Comment by NivixX** [comment]
I've been able to reproduce it with a different JDK.
You can try this update :

[](https://github.com/NivixX/NDatabase/releases/tag/0.1.6)

**Comment by RE4ERKA** [comment]
![image](https://user-images.githubusercontent.com/66727581/217158397-4b0db1fc-39f8-4f5f-963f-3c6cd0793da5.png)

Thanks, the latest version 0.1.6 is working!

**Comment by NivixX** [comment]
Perfect, let me know if you have further reflection issue using NDatabase, I'll close the issue if everything is fine.
