### ISSUE TITLE
Requires the creation of an empty constructor, but it is!

### ISSUE THREAD

**Issue by RE4ERKA** [NivixX/NDatabase#6]
PlayerData class:
```
@Getter
@Setter
@NTable(name = "player_data")
public class PlayerData extends NEntity<UUID> {

    @JsonProperty("coins")
    @Indexed
    private int coins;

    public PlayerData() { }

    public PlayerData(UUID uuid, int coins) {
        super(uuid);

        this.coins = coins;
    }
}
```

![image](https://user-images.githubusercontent.com/66727581/226937525-b6d2902a-15fb-47ee-81f0-7101d5c715ac.png)

**Comment by NivixX** [comment]
Hello, something is probably wrong between java versions.
What is the java version your spigot is running in ? and with what java version you exported your .jar plugin ?
Maybe your plugin java version doesn't match your jvm version.
As for NDatabase, it has been compiled in java 1.8, so it should work in java 1.8 and higher (tested until java 18)

**Comment by RE4ERKA** [comment]
I previously did an issue and since that time the version of java has not changed.

That is, previously the plugin worked, on version 0.1.5 NDatabase.

But I made a screenshot of the java version again:
![image](https://user-images.githubusercontent.com/66727581/226948229-10bad916-bff1-4d30-85cf-f231fb6f13dd.png)

**Comment by RE4ERKA** [comment]
No, NDatabase is located as a separate plugin on the server.

[PlayerCounter.zip](https://github.com/NivixX/NDatabase/files/11041724/PlayerCounter.zip)

**Comment by NivixX** [comment]
![image](https://user-images.githubusercontent.com/5229597/226965421-e91f8cd7-42a9-454c-855e-f193300d9cb6.png)

I just tried to use your jar with a similar configuration as yours (except I'm using oracle java 17 and not a linux build) and it works fine. I suggest you to try with a fresh server with only NDatabase and your plugin to check if you have the same issue.
The way the constructor is called is the same as in 0.1.6 so it's quite surprising, does the issue is gone if you remove the @indexed and you downgrade to 0.1.6 ?

**Comment by NivixX** [comment]
Oh ok, so as I said earlier maybe your second plugin contains the src of Ndatabase so you had a conflict.

As for the ">>" error, I realised that some PaperSpigot version was using an old SQLite driver but 3.38> is required to use JSON operators in SQLite.
I'm going to figure out the best approach for this limitation..
In the meantime you can try to change the SQLite driver yourself (usually all libs are installed into the "/libraries" folder, so the sqlite driver should be in libraries\org\xerial\sqlite-jdbc)

**Comment by NivixX** [comment]
Hello, FYI I found a way to index the database without using 3.38 > `GENERATED COLUMNS`

You can re-test your playerCounter plugin.
[https://github.com/NivixX/NDatabase/releases/tag/1.1.4](https://github.com/NivixX/NDatabase/releases/tag/1.1.4)

Also, I would advice to use other database type for more high scale servers

**Comment by NivixX** [comment]
Hello, try this one
https://github.com/NivixX/NDatabase/releases/tag/1.1.6

I will write an adapter in a near future because the driver version used in spigot are not consistent

**Comment by RE4ERKA** [comment]
Hi, it works now, thanks!
