### ISSUE TITLE
Outputs an error when retrieving data from the database.

### ISSUE THREAD

**Issue by RE4ERKA** [NivixX/NDatabase#7]
The plugin works like this, the player leaves - the data are stored in the database, the player enters - the data are obtained from the database.

When you save the data on exit - no error. But when receiving data from the database when the player enters - in the console appears such an error: https://pastebin.com/iTE7Nynu

Methods get and save:
```
public void save(DialogData data) {
  repository.upsertAsync(data);
}

public DialogData getOrCreate(UUID uuid) {
  DialogData dialogData;

  try {
    dialogData = repository.getAsync(uuid).getResultFuture().get();
  } catch (InterruptedException | ExecutionException e) {
    throw new RuntimeException(e);
  }

  return dialogData == null ? new DialogData(uuid) : dialogData;
}
```

DialogData class:
```
@NTable(name = "dialog_data")
public class DialogData extends NEntity<UUID> {
    @JsonProperty("dialogs")
    private List<DialogStatus> dialogs = new ArrayList<>();

    public DialogData(UUID uuid) {
        super(uuid);
    }

    public DialogData() { }
}
```

DialogStatus class:
```
public class DialogStatus {
    private final String name;
    private int part = 0;
    private boolean finished = false;

    public DialogStatus(String name) {
        this.name = name;
    }

    public void setPart(int part) {
        this.part = part;
    }

    public void partIncrement() {
        part++;
    }

    public void partReset() {
        part = 0;
    }

    public void finish() {
        finished = true;
    }

    public String getName() {
        return name;
    }

    public int getPart() {
        return part;
    }

    public boolean isFinished() {
        return finished;
    }
}
```

_It would be more convenient if there was a discord server where I could ask what the problem could be._

**Comment by NivixX** [comment]
Hello,

I think the issue here is that your subobject `DialogStatus` doesn't have a **default** constructor, so when NDatabase try to decode from database, you get this error.

I already planned to add a data model validation mechanism in future to avoid getting runtime encoding error but it's not finished yet.

**Comment by RE4ERKA** [comment]
Yes, it works now, thanks for the help!
